CREATE TABLE RefreshTokens (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    Token nvarchar(256) NOT NULL UNIQUE,
    UserId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_RefreshTokens_Users FOREIGN KEY (UserId)
       REFERENCES Users(Id),
    ExpiresAt DATETIME2 NOT NULL,
    IsRevoked BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL,
)

